apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "device-monitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ template "device-monitor.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "device-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        name: {{ template "device-monitor.fullname" . }}
        {{- include "device-monitor.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            
          ports:
            {{- range $key, $port := .Values.ports.grpc }}
            - name: grpc{{ $key }}
              containerPort: {{ $port }}
            {{- end}}
            
          volumeMounts:
            - name: config
              mountPath: /etc/simulator/configs
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ template "device-monitor.fullname" . }}-config
