nameOverride: ""
fullnameOverride: ""

replicaCount: 1
annotations: {}

image:
  repository: onosproject/grpc-client
  tag: v0.0.0
  pullPolicy: IfNotPresent
  pullSecrets: []

resources:
  requests:
    cpu: 0.5
    memory: 512Mi

service:
  type: ClusterIP

ports:
  grpc:
    insecure: 4040

nodeSelector: {}

tolerations: []

affinity: {}
